version: '3.3'

services:
  wordpress:
    image: experiences.azurecr.io/multicontainerwordpress
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
    ports:
       - "8000:80"
    restart: always

  redis:
    image: registry.hub.docker.com/library/redis:3-alpine
    restart: always